[package]
name = "anime-game-launcher"
version = "1.1.0"
description = "Anime Game launcher"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = 3

[build-dependencies]
gtk4 = "0.4"

[dependencies]
gtk4 = "0.4"
libadwaita = "0.1"
rfd = { version = "0.10", features = ["xdg-portal"], default-features = false }

anime-game-core = { path = "anime-game-core", features = ["all", "static", "genshin"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

dirs = "4.0.0"
wait_not_await = "0.2.1"
regex = "1.6.0"
lazy_static = "1.4.0"
anyhow = "1.0"
md5 = "0.7"
