[package]
name = "anime-game-launcher"
version = "0.2.1"
description = "Anime Game launcher"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true

[build-dependencies]
gtk4 = "0.4"

[dependencies]
gtk4 = "0.4"
libadwaita = "0.1"

anime-game-core = { path = "anime-game-core", features = ["all", "static"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

dirs = "4.0.0"
tokio = { version = "1.20", features = ["rt", "rt-multi-thread", "macros"] }
wait_not_await = "0.2.1"
regex = "1.6.0"
lazy_static = "1.4.0"
